#use root/root as user/password credentials
version: '3.1'

services:
 python:
  build: .
  volumes:
  - .:/opt/pythonProjet
  - logvolume01:/var

 db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: cryptoDB
   MYSQL_USER: nicky
   MYSQL_PASSWORD: root

 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080
  links:
   - db

volumes:
 logvolume01: {}
